[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2", "numpy>=1.19.0", "Cython>=0.29.21"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
local_scheme = "no-local-version"